name: permission_handler_android_example
description: Demonstrates how to use the permission_handler_android plugin.

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  baseflow_plugin_template: ^2.1.2
  flutter:
    sdk: flutter
  permission_handler_platform_interface: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  permission_handler_android: ^14.0.1

  url_launcher: ^6.0.12

flutter:
  uses-material-design: true

  assets:
    - res/images/baseflow_logo_def_light-02.png
    - res/images/poweredByBaseflowLogoLight@3x.png
