name: permission_handler_apple_example
description: Demonstrates how to use the permission_handler_apple plugin.

environment:
  sdk: ^3.7.0

dependencies:
  baseflow_plugin_template: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  permission_handler_apple:
    path: ../

  url_launcher: ^6.0.12

flutter:
  uses-material-design: true

config:
  enable-swift-package-manager: true
  assets:
    - res/images/baseflow_logo_def_light-02.png
    - res/images/poweredByBaseflowLogoLight@3x.png
